language: python
python:
    - "3.6"
    - "3.7.1"
install:
    - cp example.env .env
    - pip install pipenv
    - export VENV_HOME_DIR=$(pipenv --venv)
    - pipenv sync
    - pipenv shell
script:
    - python manage.py test shortener_app
