dist: "xenial"
language: python
python:
    - "3.6"
    - "3.7"
install:
    - cp example.env .env
    - pip install pipenv
    - pipenv install --dev
script:
    - pipenv manage.py test shortener_app
