dist: "xenial"
language: python
addons:
  chrome: stable
python:
    - "3.6"
    - "3.7"
install:
    - cp example.env .env
    - pip install pipenv
    - pipenv install --dev
    - pipenv run python manage.py collectstatic --no-input
script:
    - pipenv run coverage run --omit=functional_tests/*,shortener/*,manage.py,shortener_app/app.py,users/app.py,payments/app.py --source='.' manage.py test
    - codecov
