language: python
python:
    - "3.6"
    - "3.7"
env:
    - ENVIRONMENT='DEVELOPMENT'
    - DJANGO_SECRET_KEY='dont-tell-eve'
    - DJANGO_DEBUG='yes'
    - DJANGO_IPSTACK_APIKEY='apikey'
    - DJANGO_STRIPE_PUBLIC_KEY='test'
    - DJANGO_STRIPE_SECRET_KEY='test'
install:
    - pip install -r requirements.txt
script:
    - python manage.py test shortener_app
